apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/hoanghai4804/microservices-blog-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://bloguser:blogpassword@postgres:5432/blogdb"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"